### PR TITLE
Implement JSON view support for Jackson 2 branch and re-enable views test

### PR DESCRIPTION
**Pull request by benmccann**
I'd love to see the Jackson 2 branch merged into master.  Here's my contribution towards making that happen ;-)

### CODE REVIEW

**Comment by benmccann** [comment]
Hey James, I hope this is helpful.  I would really love to see this committed so that all the tests pass again!

**Comment by benmccann** [comment]
Hey James, just updated this with the latest mongodb driver, which was released along with today's MongoDB 2.2 release.  They suggest upgrading the driver before the installation though I don't know how critical that is, but still it'd be nice to get this checked in.

**Comment by benmccann** [comment]
Updated to use the latest version on Mongo and Jackson.  Would really love to get this checked in.

**Comment by pmaedel** [comment]
+1

**Comment by benmccann** [comment]
FYI, here's the corresponding request for the Play Framework. Just linking to it from here for informational purposes.
https://github.com/playframework/Play20/pull/461

**Comment by gijsk** [comment]
Note that AFAICT you can no longer associate a view with an instance of `ObjectMapper` (you just pass it when you create a writer/reader), which means that the static `.wrap` methods for creating a `JacksonDBCollection` no longer suffice: you can't pass both your own `ObjectMapper` and your own view (and both are final fields, so they can't be modified anymore post-creation of the collection instance). Could you please add another `wrap` static instantiator thingummywhatsit that allows passing both? (or just make the constructor public?)

**Comment by klette** [comment]
Would love to see this feature into master - we've started porting everything to Jackson 2.x, and this is kind of a blocker for all systems that use MongoDB

**Comment by juanformoso** [comment]
+1

We have the same need

**Comment by ESPNMichaelKidd** [comment]
+1

**Comment by olvesh** [comment]
+1

**Comment by vmorev** [comment]
Really hoping on getting this checked in soon

**Comment by jroper** [comment]
This has been included in the new MongoJack project:

http://mongojack.org

**Pull request closed without merging**
